'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {setup,attach,draft,clone}=require('./fixtures/merchant-catalog');
const {setup:orderSetup}=require('./fixtures/merchant-order');
const {createMerchantCatalogService}=require('../cloudfunctions/_shared/merchant-catalog-service');
const {createCatalogReadModel}=require('../cloudfunctions/_shared/catalog-read-model');
const {scopedDocumentId}=require('../cloudfunctions/_shared/idempotency-model');
const {PAGE_POLICY}=require('../cloudfunctions/_shared/pagination-model');
const rejects=(fn,code)=>assert.rejects(fn,error=>error.code===code);
const state=s=>JSON.stringify(s.db);
function createEvent(s,patch={}){const input=s.event('product.save');delete input.payload.productId;delete input.payload.expectedVersion;
  input.payload.draft.skus.forEach(sku=>{delete sku.skuId;delete sku.expectedVersion;sku.status='DRAFT';});
  input.payload.draft.name='新建隔离草稿';input.payload.draft.minLeadTimeMinutes=null;input.payload.draft.images=[];
  return {...input,payload:{...input.payload,...patch}};}
const currentReader=s=>createCatalogReadModel({categories:s.db.categories,products:Object.values(s.db.products),skus:Object.values(s.db.skus),mediaAssets:Object.values(s.db.mediaAssets)},
  {...s.context,storeId:s.storeId},s.options.key);

test('A04 creates deterministic draft product and SKUs with atomic audit/receipt; original key replays without extra writes',async()=>{
  const s=await setup(),event=createEvent(s),result=await s.catalogService.execute(event,s.initial),id=result.result.entityId;
  assert.equal(s.db.products[id].status,'DRAFT');assert.equal(s.db.products[id].minLeadTimeMinutes,null);assert.equal(s.db.products[id].version,0);
  assert.equal(s.controls.lastWrites,4);const before=state(s);
  const rebuilt=createMerchantCatalogService(s.options);assert.equal((await rebuilt.execute(event,s.initial)).disposition,'REPLAY');assert.equal(state(s),before);
  const item=Object.values(s.db.skus).find(sku=>sku.productId===id);assert.equal(item.status,'DRAFT');assert.equal(item.version,0);
  assert.equal(currentReader(s).productsList({storeId:s.storeId},s.controls.now).items.length,1);
});

test('A04 price edits update only product and changed SKU versions; counts, media and original entities stay independent',async()=>{
  const s=await setup(),event=s.event('product.save'),stock=clone(s.db.resources),media=clone(s.db.mediaAssets);
  event.payload.draft.skus[0].unitPriceCents=1200;const result=await s.catalogService.execute(event,s.member);
  assert.equal(result.result.version,1);assert.equal(s.db.skus.sku.version,1);assert.equal(s.controls.lastWrites,4);
  assert.deepEqual(s.db.resources,stock);assert.deepEqual(s.db.mediaAssets,media);
  const product=currentReader(s).productGet({productId:'product'});assert.equal(product.skus[0].unitPriceCents,1200);assert.equal(product.version,1);
  const stable=state(s);assert.equal((await s.catalogService.execute(event,s.member)).disposition,'REPLAY');assert.equal(state(s),stable);
});

test('A04 unchanged SKUs keep versions while product metadata edits increment the parent and retain private server fields',async()=>{
  const s=await setup();s.db.products.product.privateAdminNote='KEEP_PRIVATE';s.db.skus.sku.privateFlag='KEEP_PRIVATE_SKU';
  const event=s.event('product.save');event.payload.draft.name='已修改名称';await s.catalogService.execute(event,s.initial);
  assert.equal(s.db.products.product.version,1);assert.equal(s.db.skus.sku.version,0);assert.equal(s.controls.lastWrites,3);
  assert.equal(s.db.products.product.privateAdminNote,'KEEP_PRIVATE');assert.equal(s.db.skus.sku.privateFlag,'KEEP_PRIVATE_SKU');
});

test('A04 new explicit variants are generated by server and duplicate combinations or replacing existing IDs are refused',async()=>{
  const s=await setup(),event=s.event('product.save'),source=clone(event.payload.draft.skus[0]);delete source.skuId;delete source.expectedVersion;
  source.selectedOptions[0].optionCode='LARGE';source.selectedOptions[0].label='client forged label';event.payload.draft.skus.push(source);
  await s.catalogService.execute(event,s.initial);const variants=Object.values(s.db.skus);assert.equal(variants.length,2);
  assert.equal(variants.find(sku=>sku._id!=='sku').selectedOptions[0].label,'测试大尺寸');
  const other=await setup(),bad=other.event('product.save'),copy=clone(bad.payload.draft.skus[0]);delete copy.skuId;delete copy.expectedVersion;
  bad.payload.draft.skus.push(copy);await rejects(()=>other.catalogService.execute(bad,other.initial),'INVALID_SELECTION');
});

test('A04 category/SKU combination and archived variant are immutable; omission cannot hard-delete referenced SKUs',async()=>{
  for(const [change,code] of [[event=>event.payload.draft.categoryCode='BREAD','IMMUTABLE_CATALOG_FIELD'],
    [event=>event.payload.draft.skus[0].selectedOptions[0].optionCode='LARGE','IMMUTABLE_CATALOG_FIELD'],
    [event=>{const item=clone(event.payload.draft.skus[0]);delete item.skuId;delete item.expectedVersion;event.payload.draft.skus=[item];},'SKU_REMOVAL_FORBIDDEN']]){
    const s=await setup(),event=s.event('product.save'),before=state(s);change(event);await rejects(()=>s.catalogService.execute(event,s.initial),code);assert.equal(state(s),before);
  }
  const s=await setup();s.db.skus.sku.status='ARCHIVED';s.db.products.product.status='OFF_SALE';
  const event=s.event('product.save');event.payload.draft.skus[0].unitPriceCents=1200;await rejects(()=>s.catalogService.execute(event,s.initial),'IMMUTABLE_CATALOG_FIELD');
});

test('A04 only three categories, explicit integer cents, valid groups, quantity/message and stock configurations can be saved',async()=>{
  const mutations=[event=>event.payload.draft.categoryCode='DRINK',event=>event.payload.draft.skus[0].unitPriceCents=1.5,
    event=>event.payload.draft.skus[0].minQuantity=0,event=>event.payload.draft.skus[0].maxQuantity=0,event=>event.payload.draft.skus[0].currency='USD',
    event=>event.payload.draft.skus[0].selectedOptions=[],event=>event.payload.draft.skus[0].stockRequirements.push(clone(event.payload.draft.skus[0].stockRequirements[0])),
    event=>event.payload.draft.optionGroups[0].options.push(clone(event.payload.draft.optionGroups[0].options[0])),
    event=>event.payload.draft.messagePolicy={maxLength:0,normalizationVersion:'unknown'},event=>event.payload.draft.minLeadTimeMinutes=-1];
  for(const change of mutations){const s=await setup(),event=s.event('product.save'),before=state(s);change(event);await assert.rejects(()=>s.catalogService.execute(event,s.initial));assert.equal(state(s),before);}
});

test('A04 draft null price/quantity/leadtime and empty stock/images remain incomplete and never become published defaults',async()=>{
  const s=await setup(),event=createEvent(s),sku=event.payload.draft.skus[0];sku.unitPriceCents=null;sku.minQuantity=null;sku.maxQuantity=null;sku.stockRequirements=[];
  const saved=await s.catalogService.execute(event,s.initial),productId=saved.result.entityId,before=state(s);
  await assert.rejects(()=>s.execute('product.status.set',{productId,expectedVersion:0,status:'ON_SALE'}));assert.equal(state(s),before);
  assert.equal(s.db.products[productId].minLeadTimeMinutes,null);assert.equal(Object.values(s.db.skus).find(sku=>sku.productId===productId).unitPriceCents,null);
});

test('A04 on-sale validation requires published real-photo registration, explicit SKU limits, leadtime, open stock and category',async()=>{
  const cases=[s=>s.db.mediaAssets[Object.keys(s.db.mediaAssets)[0]].status='DRAFT',s=>s.db.mediaAssets[Object.keys(s.db.mediaAssets)[0]].status='RETIRED',
    s=>{s.db.mediaAssets[Object.keys(s.db.mediaAssets)[0]].sourceKind='DESIGN_PREVIEW';s.db.products.product.images[0].sourceKind='DESIGN_PREVIEW';},
    s=>s.db.products.product.images=[],s=>s.db.products.product.minLeadTimeMinutes=null,s=>s.db.skus.sku.maxQuantity=null,
    s=>s.db.skus.sku.unitPriceCents=null,s=>s.db.skus.sku.stockRequirements=[],s=>s.db.resources.stock.status='CLOSED',s=>s.db.categories[0].published=false];
  for(const mutate of cases){const s=await setup();s.db.products.product.status='OFF_SALE';mutate(s);const before=state(s);
    await assert.rejects(()=>s.execute('product.status.set',{status:'ON_SALE'}));assert.equal(state(s),before);}
});

test('A04 off-sale/relist/archive are versioned, do not release stock or delete media and archival is terminal',async()=>{
  const s=await setup(),resources=clone(s.db.resources),media=clone(s.db.mediaAssets);
  const first=s.event('product.status.set');await s.catalogService.execute(first,s.initial);assert.equal(currentReader(s).productsList({storeId:s.storeId},s.controls.now).items.length,0);
  await s.execute('product.status.set',{status:'ON_SALE',idempotencyKey:'OFFLINE_RELIST_KEY'});assert.equal(currentReader(s).productsList({storeId:s.storeId},s.controls.now).items.length,1);
  await s.execute('product.status.set',{status:'ARCHIVED',idempotencyKey:'OFFLINE_ARCHIVE_KEY'});assert.equal(s.db.skus.sku.status,'ON_SALE');
  await rejects(()=>s.execute('product.status.set',{status:'ON_SALE',idempotencyKey:'OFFLINE_UNARCHIVE_KEY'}),'INVALID_TRANSITION');
  await rejects(()=>s.execute('product.save'),'VERSION_CONFLICT');
  assert.equal((await s.catalogService.execute(first,s.initial)).disposition,'REPLAY');assert.deepEqual(s.db.resources,resources);assert.deepEqual(s.db.mediaAssets,media);
});

test('A04 inventory lower bound includes held+confirmed+consumed; equality and CLOSED-resource totals are valid without resetting counters',async()=>{
  const s=await setup(),before=state(s);await rejects(()=>s.execute('inventory.setTotal',{totalUnits:8}),'RESOURCE_UNAVAILABLE');assert.equal(state(s),before);
  const old=clone(s.db.resources.stock),event=s.event('inventory.setTotal',{totalUnits:9});await s.catalogService.execute(event,s.initial);
  assert.equal(s.db.resources.stock.totalUnits,9);assert.equal(s.db.resources.stock.version,1);assert.equal(s.controls.lastWrites,3);
  for(const field of ['unit','storeId','name','heldUnits','confirmedUnits','consumedUnits','status','createdAt'])assert.equal(s.db.resources.stock[field],old[field]);
  const after=state(s);assert.equal((await s.catalogService.execute(event,s.initial)).disposition,'REPLAY');assert.equal(state(s),after);
  s.db.resources.stock.status='CLOSED';await s.execute('inventory.setTotal',{totalUnits:10,idempotencyKey:'OFFLINE_CLOSED_STOCK_KEY'});assert.equal(s.db.resources.stock.status,'CLOSED');
});

test('A04 no resource unit/store/counters, raw metadata, status or authority fields can be injected via maintenance inputs',async()=>{
  for(const patch of [{heldUnits:0},{unit:'new'},{storeId:'other'},{actor:{type:'STORE'}},{status:'OPEN'},{totalUnits:1.5}]){
    const s=await setup(),before=state(s);await rejects(()=>s.execute('inventory.setTotal',patch),'INVALID_REQUEST');assert.equal(state(s),before);
  }
  for(const mutation of [draft=>draft.status='ON_SALE',draft=>draft.ownerId='spoof',draft=>draft.skus[0].version=99]){
    const s=await setup(),event=s.event('product.save'),before=state(s);mutation(event.payload.draft);await assert.rejects(()=>s.catalogService.execute(event,s.initial));assert.equal(state(s),before);
  }
});

test('A04 ordinary/spoofed, cross-store and wrong capability actors cannot read related catalog or write',async()=>{
  for(const actor of ['other','spoof']){const s=await setup(),before=state(s),principal=actor==='spoof'?{...s.initial}:s.other;
    await assert.rejects(()=>s.execute('product.save',{},principal));assert.equal(s.controls.catalogReads,0);assert.equal(state(s),before);}
  const s=await setup();await rejects(()=>s.execute('products.list',{storeId:'offline-store-b'}),'FORBIDDEN');assert.equal(s.controls.catalogReads,0);
  const event=s.event('product.save',{storeId:'offline-store-b'});await rejects(()=>s.catalogService.execute(event,s.initial),'NOT_FOUND');assert.equal(s.controls.catalogReads,0);
});

test('A04 disabled user, revoked grant and archived store are checked again before replay, with strict A01 scope',async()=>{
  for(const [mutate,code] of [[s=>s.db.users[s.initial.subjectId].status='DISABLED','USER_DISABLED'],
    [s=>s.db.stores[s.storeId].status='ARCHIVED','NOT_FOUND'],
    [s=>s.controls.statePatch=access=>access.roles[0].environment='foreign','INVALID_ROLE_RECORD']]){
    const s=await setup(),event=s.event('product.save');await s.catalogService.execute(event,s.initial);mutate(s);
    const before=state(s);await rejects(()=>s.catalogService.execute(event,s.initial),code);assert.equal(state(s),before);
  }
  const s=await setup(),event=s.event('product.save');await s.catalogService.execute(event,s.member);
  const role=Object.values(s.db.roles).find(role=>role.subjectId===s.member.subjectId);
  await s.service.execute(s.revoke(role._id),s.initial);await rejects(()=>s.catalogService.execute(event,s.member),'NOT_FOUND');
});

test('A04 stale parent or child versions and same-key changed input fail without partial writes',async()=>{
  const s=await setup(),before=state(s);await rejects(()=>s.execute('product.save',{expectedVersion:1}),'VERSION_CONFLICT');assert.equal(state(s),before);
  const first=s.event('product.save');first.payload.draft.skus[0].expectedVersion=9;await rejects(()=>s.catalogService.execute(first,s.initial),'VERSION_CONFLICT');
  const event=s.event('product.save');await s.catalogService.execute(event,s.initial);event.payload.draft.name='changed';await rejects(()=>s.catalogService.execute(event,s.initial),'IDEMPOTENCY_KEY_REUSED');
});

test('A04 every product/SKU/audit/receipt write failure and zero-row result rolls back the whole edit',async()=>{
  for(const operation of ['create','edit','status','inventory'])for(const mode of ['failureAt','zeroAt'])for(let position=1;position<=(operation==='create'||operation==='edit'?4:3);position++){
    const s=await setup(),event=operation==='create'?createEvent(s):s.event(operation==='edit'?'product.save':operation==='status'?'product.status.set':'inventory.setTotal');
    if(operation==='edit')event.payload.draft.skus[0].unitPriceCents=1200;
    const before=state(s);s.controls[mode]=position;await assert.rejects(()=>s.catalogService.execute(event,s.initial));assert.equal(state(s),before);
  }
});

test('A04 role/user/store/media/resource or phantom query changes at commit prevent all catalog writes',async()=>{
  const mutations=[db=>db.users[Object.keys(db.users)[0]].version++,db=>db.stores['offline-store-a'].status='ARCHIVED',
    db=>db.resources.stock.heldUnits++,db=>db.mediaAssets[Object.keys(db.mediaAssets)[0]].status='RETIRED',
    db=>{const sku=clone(db.skus.sku);sku._id='phantom';db.skus.phantom=sku;},db=>db.roles[Object.keys(db.roles)[0]].version++];
  for(const mutate of mutations){const s=await setup();s.controls.beforeCommit=mutate;const old=clone(s.db.products.product);
    await rejects(()=>s.execute('product.save'),'VERSION_CONFLICT');assert.deepEqual(s.db.products.product,old);}
  const s=await setup();s.controls.fenceFalse=true;await rejects(()=>s.execute('inventory.setTotal'),'VERSION_CONFLICT');
});

test('A04 two serialized editors or stock setters on the same version commit only once',async()=>{
  for(const action of ['product.save','inventory.setTotal']){const s=await setup(),event=s.event(action),other=clone(event);other.payload.idempotencyKey+='SECOND';
    const results=await Promise.allSettled([s.catalogService.execute(event,s.initial),s.catalogService.execute(other,s.member)]);
    assert.equal(results.filter(result=>result.status==='fulfilled').length,1);assert.equal(results.find(result=>result.status==='rejected').reason.code,'VERSION_CONFLICT');
    assert.equal((action==='product.save'?s.db.products.product:s.db.resources.stock).version,1);}
});

test('A04 malformed scoped state, duplicate/missing child, unsafe resources, foreign stock and damaged media are rejected',async()=>{
  const patches=[state=>state.complete=false,state=>state.environment='other',state=>state.appId='other',state=>state.storeId='other',
    state=>state.products.push(clone(state.products[0])),state=>state.skus=[],state=>state.skus[0].storeId='other',
    state=>state.resources[0].heldUnits=Number.MAX_SAFE_INTEGER,state=>state.resources[0].unit='',state=>state.mediaAssets[0].contentHash='bad'];
  for(const patch of patches){const s=await setup(),before=state(s);s.controls.catalogStatePatch=patch;
    await assert.rejects(()=>s.execute('product.get'));assert.equal(state(s),before);}
});

test('A04 merchant DTOs omit private notes, image metadata, user details and audit/receipt records',async()=>{
  const s=await setup();s.db.products.product.private='PRIVATE_PRODUCT';s.db.skus.sku.private='PRIVATE_SKU';s.db.resources.stock.private='PRIVATE_STOCK';s.db.mediaAssets[Object.keys(s.db.mediaAssets)[0]].private='PRIVATE_MEDIA';
  for(const action of ['product.get','products.list','inventory.list']){const result=await s.execute(action),value=JSON.stringify(result);
    assert(!/PRIVATE_|openId|contentHash|byteLength|actorScope|idempotencyKey/.test(value));
    for(const gate of ['cloudVerified','callable','operationsAllowed'])assert.equal(result[gate],false);assert(Object.isFrozen(result));}
});

test('A04 stable merchant pagination is scoped to current actor/grant/store/filter/content and handles equal anchors',async()=>{
  const s=await setup();for(let index=1;index<5;index++){const product=clone(s.db.products.product);product._id='product-'+index;s.db.products[product._id]=product;
    const sku=clone(s.db.skus.sku);sku._id='sku-'+index;sku.productId=product._id;s.db.skus[sku._id]=sku;}
  const first=await s.execute('products.list',{pageSize:2});assert.equal(first.items.length,2);assert(first.nextCursor);
  const next=await s.execute('products.list',{pageSize:3,cursor:first.nextCursor});assert.equal(next.items.length,3);assert.equal(next.hasMore,false);
  assert.equal(new Set([...first.items,...next.items].map(product=>product._id)).size,5);
  await rejects(()=>s.execute('products.list',{cursor:first.nextCursor},s.member),'CURSOR_INVALID');
  await rejects(()=>s.execute('products.list',{cursor:first.nextCursor,status:'ON_SALE'}),'CURSOR_INVALID');
  s.db.products.product.version++;await rejects(()=>s.execute('products.list',{cursor:first.nextCursor}),'CURSOR_INVALID');
});

test('A04 inventory pagination, tampered/expired cursor and header-to-snapshot mismatch fail closed',async()=>{
  const s=await setup();for(let index=1;index<3;index++){const item=clone(s.db.resources.stock);item._id='stock-'+index;s.db.resources[item._id]=item;}
  const first=await s.execute('inventory.list',{pageSize:1}),next=await s.execute('inventory.list',{cursor:first.nextCursor});assert.equal(next.items.length,2);
  await rejects(()=>s.execute('inventory.list',{cursor:first.nextCursor+'x'}),'CURSOR_INVALID');
  s.controls.now+=PAGE_POLICY.cursorTtlMs;await rejects(()=>s.execute('inventory.list',{cursor:first.nextCursor}),'CURSOR_EXPIRED');
  s.controls.catalogStatePatch=state=>state.products[0].version++;await rejects(()=>s.execute('product.get'),'VERSION_CONFLICT');
});

test('A04 audit and replay proofs reject tampering and sanitized reason never copies raw phone or a draft',async()=>{
  for(const change of [audit=>audit.actor.subjectId='other',audit=>audit.target.afterVersion++,audit=>audit.changes[0].after='a'.repeat(64),audit=>audit.changes[1].after='a'.repeat(64),audit=>audit.createdAt--]){
    const s=await setup(),event=s.event('inventory.setTotal');await s.catalogService.execute(event,s.initial);
    const receipt=Object.values(s.db.receipts).find(receipt=>receipt.command==='admin.inventory.setTotal'),id=scopedDocumentId('merchant-catalog-audit',[receipt._id]);
    assert(!JSON.stringify(s.db.audits[id]).includes('13800138000'));change(s.db.audits[id]);await rejects(()=>s.catalogService.execute(event,s.initial),'INVALID_IDEMPOTENCY_RECORD');
  }
});

test('A04 server clock rollback and version increment overflow cannot commit catalog/resource changes',async()=>{
  const s=await setup(),before=state(s);s.controls.nowSequence=[s.controls.now,s.controls.now,s.controls.now-1];
  await rejects(()=>s.execute('inventory.setTotal'),'INVALID_CONFIGURATION');assert.equal(state(s),before);
  for(const kind of ['product','sku','stock']){const x=await setup();(kind==='product'?x.db.products.product:kind==='sku'?x.db.skus.sku:x.db.resources.stock).version=Number.MAX_SAFE_INTEGER;
    const event=x.event(kind==='stock'?'inventory.setTotal':'product.save');if(kind==='sku')event.payload.draft.skus[0].unitPriceCents=1200;
    await rejects(()=>x.catalogService.execute(event,x.initial),'VERSION_CONFLICT');}
});

test('A04 replay version and deterministic created identity remain bound to the original request despite later changes',async()=>{
  for(const kind of ['version','identity']){
    const s=await setup(),event=kind==='identity'?createEvent(s):s.event('inventory.setTotal');await s.catalogService.execute(event,s.initial);
    const receipt=Object.values(s.db.receipts).find(receipt=>receipt.command==='admin.'+event.action),auditId=scopedDocumentId('merchant-catalog-audit',[receipt._id]),audit=s.db.audits[auditId];
    if(kind==='version'){
      await s.execute('inventory.setTotal',{totalUnits:15,idempotencyKey:'OFFLINE_STOCK_LATER_EDIT'});
      const liveReceipt=s.db.receipts[receipt._id],liveAudit=s.db.audits[auditId];
      liveReceipt.result.version=2;liveAudit.target.beforeVersion=1;liveAudit.target.afterVersion=2;
      const {resourceDTO}=require('../cloudfunctions/_shared/merchant-catalog-model'),{requestFingerprint}=require('../cloudfunctions/_shared/idempotency-model');
      liveAudit.changes[1].after=requestFingerprint(resourceDTO(s.db.resources.stock));
    }else{
      const previous=s.db.products[receipt.result.entityId],newId='altered-created-product';delete s.db.products[previous._id];s.db.products[newId]={...previous,_id:newId};
      for(const sku of Object.values(s.db.skus))if(sku.productId===previous._id)sku.productId=newId;
      receipt.result.entityId=newId;audit.target.entityId=newId;
      const {productDTO}=require('../cloudfunctions/_shared/merchant-catalog-model'),{requestFingerprint}=require('../cloudfunctions/_shared/idempotency-model');
      audit.changes[1].after=requestFingerprint(productDTO(s.db.products[newId],Object.values(s.db.skus).filter(sku=>sku.productId===newId)));
    }
    await rejects(()=>s.catalogService.execute(event,s.initial),'INVALID_IDEMPOTENCY_RECORD');
  }
});

test('A04 image replacement keeps old immutable asset revision, rejects unregistered references and never mutates asset metadata',async()=>{
  const s=await setup(),old=Object.values(s.db.mediaAssets)[0],next={...clone(old),_id:scopedDocumentId('media',[s.context.environment,old.assetId,'v2']),revision:'v2',storageRef:s.context.allowedCloudPrefixes[0]+'next.png'};
  s.db.mediaAssets[next._id]=next;const before=clone(s.db.mediaAssets),event=s.event('product.save');
  event.payload.draft.images=[{assetId:next.assetId,revision:next.revision,storageRef:next.storageRef,sourceKind:next.sourceKind}];
  await s.catalogService.execute(event,s.initial);assert.deepEqual(s.db.mediaAssets,before);assert.equal(s.db.products.product.images[0].revision,'v2');
  const bad=s.event('product.save',{idempotencyKey:'OFFLINE_IMAGE_UNKNOWN_VERSION'});bad.payload.draft.images[0].revision='missing';
  await rejects(()=>s.catalogService.execute(bad,s.initial),'MEDIA_VERSION_UNAVAILABLE');assert.deepEqual(s.db.mediaAssets,before);
});

test('A04 last on-sale variant cannot be archived while parent remains on sale, but explicit off-sale permits safe SKU archival',async()=>{
  const s=await setup(),event=s.event('product.save');event.payload.draft.skus[0].status='ARCHIVED';
  await rejects(()=>s.catalogService.execute(event,s.initial),'CONFIGURATION_REQUIRED');assert.equal(s.db.skus.sku.status,'ON_SALE');
  await s.execute('product.status.set');const next=s.event('product.save');next.payload.draft.skus[0].status='ARCHIVED';
  await s.catalogService.execute(next,s.initial);assert.equal(s.db.skus.sku.status,'ARCHIVED');
  assert.equal((await s.execute('product.get')).skus[0].status,'ARCHIVED');
});

test('A04 authorized empty-store lists and no-op status requests have explicit results without inventing resources',async()=>{
  const s=await setup();await s.service.execute(s.grant({subjectId:s.other.subjectId,storeIds:[s.storeId],capabilities:['CATALOG_WRITE'],idempotencyKey:'OFFLINE_EMPTY_OBSERVER_GRANT'}),s.initial);
  await rejects(()=>s.execute('product.status.set',{status:'ON_SALE'}),'INVALID_TRANSITION');
  await rejects(()=>s.execute('product.status.set',{status:'DRAFT'}),'INVALID_TRANSITION');
  delete s.db.products.product;delete s.db.skus.sku;delete s.db.resources.stock;
  for(const action of ['products.list','inventory.list']){const result=await s.execute(action,{},s.other);assert.equal(result.items.length,0);assert.equal(result.nextCursor,null);assert.equal(result.hasMore,false);}
});

test('A04 actual cloud adapter keeps all catalog/inventory maintenance actions blocked before platform initialization',async()=>{
  const {createClient}=require('../miniprogram/services/cloud');let calls=0;
  const client=createClient({mode:'cloud',stage:'test',cloudEnvironments:{test:'OFFLINE_GATE'}},()=>({cloud:{init(){calls++;},callFunction(){calls++;}}}),{warn(){}});
  for(const action of ['product.save','product.status.set','inventory.setTotal','products.list','product.get','inventory.list'])
    await rejects(()=>client.call('admin',action,{}),'INVALID_REQUEST');assert.equal(calls,0);
});

async function integration(){
  const s=await orderSetup(),context={...s.context,stage:'test',allowedCloudPrefixes:['cloud://offline-X05/catalog/']},at=s.controls.now-1000,products={},skus={},resources={};
  for(const entry of s.db.catalogs){const product={...entry.product,schemaVersion:1,createdAt:at,updatedAt:at,description:'隔离目录',sortOrder:0};products[product._id]=product;
    for(const value of entry.skus)skus[value._id]={...value,schemaVersion:1,createdAt:at,updatedAt:at};}
  for(const value of Object.values(s.db.stocks))resources[value._id]={...value,schemaVersion:1,createdAt:at,updatedAt:at,name:'隔离资源',unit:'OFFLINE_TEST_UNIT'};
  const added=attach(s,context,products,skus,resources);for(const product of Object.values(s.db.products))product.images=[clone(added.image)];
  s.db.catalogs=s.db.catalogs.map(entry=>({product:clone(s.db.products[entry.product._id]),skus:entry.skus.map(sku=>clone(s.db.skus[sku._id]))}));s.db.stocks=clone(s.db.resources);
  const hook=s.controls.extendTransaction;
  s.controls.extendTransaction=parts=>{const tx=hook(parts);return {...tx,
    saveProduct:async(record,version)=>{const result=await tx.saveProduct(record,version);parts.staged.catalogs.find(entry=>entry.product._id===record._id).product=clone(record);return result;},
    saveSku:async(record,version)=>{const result=await tx.saveSku(record,version),entry=parts.staged.catalogs.find(entry=>entry.product._id===record.productId);entry.skus=entry.skus.map(sku=>sku._id===record._id?clone(record):sku);return result;},
    saveInventory:async(record,version)=>{const result=await tx.saveInventory(record,version);parts.staged.stocks[record._id]=clone(record);return result;}};};
  const product=Object.values(s.db.products)[0],skusFor=()=>Object.values(s.db.skus).filter(sku=>sku.productId===product._id);
  const save=()=>({action:'product.save',payload:{storeId:s.storeId,productId:product._id,expectedVersion:s.db.products[product._id].version,
    draft:draft(s.db.products[product._id],skusFor()),idempotencyKey:'OFFLINE_INTEGRATED_CATALOG_SAVE'}});
  return {...s,...added,context,save,productId:product._id};
}

test('A04 actual local price edit invalidates an existing O03 quote, leaving created order facts/logs/payments/media unchanged',async()=>{
  const s=await integration(),quote=s.makeQuote({key:'OFFLINE_BEFORE_PRICE_CREATE'}),before=clone({orders:s.db.orders,items:s.db.items,logs:s.db.logs,payments:s.db.payments,media:s.db.mediaAssets});
  const event=s.save();event.payload.draft.skus[0].unitPriceCents+=100;await s.catalogService.execute(event,s.primary);
  await rejects(()=>s.service.execute(quote.event,quote.customer),'QUOTE_CHANGED');assert.deepEqual({orders:s.db.orders,items:s.db.items,logs:s.db.logs,payments:s.db.payments,media:s.db.mediaAssets},before);
});

test('A04 actual local off-sale invalidates O03 buying and preserves historical orders and confirmed stock reservations',async()=>{
  const s=await integration(),quote=s.makeQuote({key:'OFFLINE_BEFORE_OFFSALE_CREATE'}),before=clone([s.db.orders,s.db.items,s.db.reservations,s.db.stocks,s.db.mediaAssets]);
  await s.catalogService.execute({action:'product.status.set',payload:{productId:s.productId,expectedVersion:s.db.products[s.productId].version,status:'OFF_SALE',reason:'隔离下架',idempotencyKey:'OFFLINE_INTEGRATED_OFFSALE'}},s.primary);
  await assert.rejects(()=>s.service.execute(quote.event,quote.customer));assert.deepEqual([s.db.orders,s.db.items,s.db.reservations,s.db.stocks,s.db.mediaAssets],before);
});

test('A04 actual local inventory total version invalidates O03 quote without releasing existing held/confirmed/consumed units',async()=>{
  const s=await integration(),quote=s.makeQuote({key:'OFFLINE_BEFORE_TOTAL_CREATE'}),resource=Object.values(s.db.resources)[0],before=clone(s.db.reservations),counts=clone(resource);
  await s.catalogService.execute({action:'inventory.setTotal',payload:{resourceId:resource._id,expectedVersion:resource.version,totalUnits:resource.totalUnits+5,reason:'隔离补货',idempotencyKey:'OFFLINE_INTEGRATED_TOTAL'}},s.primary);
  await rejects(()=>s.service.execute(quote.event,quote.customer),'QUOTE_CHANGED');assert.deepEqual(s.db.reservations,before);
  for(const field of ['heldUnits','confirmedUnits','consumedUnits'])assert.equal(s.db.stocks[resource._id][field],counts[field]);
});
