const api = require('../../utils/api'); const view = require('../../utils/view');
Page({
  data: { authorized:false,pin:'',tab:'orders',orders:[],products:[],notifications:[],unread:0,settings:{},metrics:{confirm:0,deposit:0,active:0,requests:0},editing:null,sizeText:'',flavorText:'',error:'',busy:false },
  onShow(){this.load();this.timer=setInterval(()=>{if(this.data.authorized&&this.data.tab==='orders'&&!this.data.busy)this.load();},15000);},onHide(){clearInterval(this.timer);},onUnload(){clearInterval(this.timer);},
  async load(){try{await api.ready();if(!wx.getStorageSync('jjl_staff'))return;await api.request('/me','GET',undefined,'staff');const [orders,products,notifications,config]=await Promise.all([api.request('/orders','GET',undefined,'staff'),api.request('/products','GET',undefined,'staff'),api.request('/notifications','GET',undefined,'staff'),api.request('/config')]);this.setData({authorized:true,orders:orders.map(view.order),products:products.map(view.product),notifications,unread:notifications.filter(n=>!n.read).length,settings:config.shop,metrics:{confirm:orders.filter(o=>o.status==='WAIT_CONFIRM').length,deposit:orders.filter(o=>o.status==='WAIT_DEPOSIT').length,active:orders.filter(o=>['RESERVED','MAKING','READY','DELIVERING'].includes(o.status)).length,requests:orders.filter(o=>o.request).length},error:''});}catch(e){if(e.status===401){wx.removeStorageSync('jjl_staff');this.setData({authorized:false});}else api.fail(this,e);}},
  input(e){this.setData({[e.currentTarget.dataset.field]:e.detail.value});},
  async login(){await api.run(this,async()=>{const session=await api.request('/staff/login','POST',{pin:this.data.pin},'staff');wx.setStorageSync('jjl_staff',session.token);this.setData({pin:''});await this.load();});},
  async logout(){await api.run(this,async()=>{await api.request('/logout','POST',{},'staff');wx.removeStorageSync('jjl_staff');this.setData({authorized:false,orders:[],products:[],notifications:[],settings:{},editing:null});});},
  async tab(e){const tab=e.currentTarget.dataset.tab;this.setData({tab,editing:null});if(tab==='notifications')await api.run(this,async()=>{await api.request('/notifications/read','POST',{},'staff');await this.load();});},
  open(e){wx.navigateTo({url:'/pages/order/order?id='+e.currentTarget.dataset.id+'&role=staff'});},
  edit(e){const product=this.data.products.find(p=>p.id===e.currentTarget.dataset.id);this.setData({editing:product,sizeText:product.sizes.map(s=>s.name+':'+s.priceCents/100).join('\n'),flavorText:product.flavors.join('\n')});},
  closeEdit(){this.setData({editing:null});},
  editInput(e){this.setData({['editing.'+e.currentTarget.dataset.field]:e.detail.value});},onSale(e){this.setData({'editing.onSale':e.detail.value});},
  async saveProduct(){await api.run(this,async()=>{const p=this.data.editing;const sizes=this.data.sizeText.split('\n').filter(x=>x.trim()).map(line=>{const values=line.split(/[:：]/);if(values.length!==2||!/^\d+(\.\d{1,2})?$/.test(values[1].trim()))throw new Error('规格应写为“6寸:200”，价格最多两位小数');return{name:values[0].trim(),priceCents:Math.round(Number(values[1])*100)};});await api.request('/products/'+p.id,'PUT',{name:p.name,subtitle:p.subtitle,description:p.description,onSale:p.onSale,sizes,flavors:this.data.flavorText.split('\n').filter(x=>x.trim())},'staff');this.setData({editing:null});await this.load();wx.showToast({title:'商品已保存',icon:'success'});});},
  settingsInput(e){this.setData({['settings.'+e.currentTarget.dataset.field]:e.detail.value});},
  settingsTime(e){this.setData({['settings.'+e.currentTarget.dataset.field]:e.detail.value});},
  async saveSettings(){await api.run(this,async()=>{await api.request('/settings','PUT',this.data.settings,'staff');await this.load();wx.showToast({title:'设置已保存',icon:'success'});});}
});
